name: jafjaf
description: ''
version: 0.0.1-SNAPSHOT
author: kishore@simpledatalabs.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/TestAirflow:
    name: TestAirflow
    description: Airflow Test Job
    fabricUID: 2160
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-07-18 19:47:46'
    author: nathan@prophecy.io
functions:
  author: null
  createdAt: '2023-04-12 15:34:56'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema: null
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/CustomerOrders:
    name: CustomerOrders
    schema: null
    description: null
    author: nathan@prophecy.io
    files:
    - models/CustomerOrders.sql
    - .prophecy/ide/models/CustomerOrders.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-07-18 19:26:04'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema: null
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: maciej@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema: null
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: maciej@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema: null
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema: null
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-04-12 15:35:01'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      providerType: Trino
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      providerType: Trino
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      providerType: Trino
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2023-04-12 15:35:01'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: kishore@simpledatalabs.com
  author: kishore@simpledatalabs.com
  createdAt: '2022-12-09 05:43:56'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
