WITH ORDERS AS (

  SELECT * 
  
  FROM {{ source('JAFFLE_SHOP.public', 'ORDERS') }}

),

CUSTOMERS AS (

  SELECT * 
  
  FROM {{ source('JAFFLE_SHOP.public', 'CUSTOMERS') }}

),

UsingCustomerId AS (

  SELECT 
    ORDERS.AMOUNT AS AMOUNT,
    CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
    ORDERS.ORDER_DATE AS ORDER_DATE
  
  FROM CUSTOMERS
  INNER JOIN ORDERS
     ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID

),

UserReport AS (

  SELECT 
    sum(AMOUNT) AS AMOUNT,
    max(ORDER_DATE) AS LAST_ORDER_DATE,
    CUSTOMER_ID AS CUSTOMER_ID,
    min(ORDER_DATE) AS FIRST_ORDER_DATE
  
  FROM UsingCustomerId AS in0
  
  GROUP BY CUSTOMER_ID

)

SELECT * 

FROM UserReport
